version: '2'
services:
  presto:
    build: .
    shm_size: 2gb
    container_name: simpipe
    volumes:
     - ~/work/simdata:/software/simPipe/simdata
     - ~/work/result:/software/simPipe/result
     - ~/work/fastdata:/software/simPipe/fastdata
     - ~/work/simBinarydata:/software/simPipe/simBinarydata
     - ~/work/config:/software/simPipe/config
     - /tmp/.X11-unix:/tmp/.X11-unix:ro
     - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
     - DISPLAY=$DISPLAY
    hostname: localhost
    expose:
     - "22"
    ports:
     - "2220:22/tcp"
    image: "simpipe:base"
    command: "/usr/sbin/sshd -D"  
    tty: false
